# Generated by Django 4.0.6 on 2022-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('texto_corto', models.CharField(max_length=40)),
                ('texto_largo', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
