# Generated by Django 4.0.6 on 2022-09-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_chat_chatform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatform',
        ),
    ]
